### ISSUE TITLE
Ask for endpoint with random port

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#79]
It would be useful to ask for a connection at a random unused port.  This is handy when making several connections from the same machine where you don't care much about what port is used, as long as it is not already taken.  In TCP-based systems port 0 is often used for this.

I think that @quasiben already brought this up informally, I just wanted to have something here for tracking.

**Comment by Akshay-Venkatesh** [comment]
@mrocklin checked to see if passing sockaddr with port 0 to `ucp_listener` at just UCX C-level works but tests show otherwise. We may need to add this functionality in UCX. 

Out of curiosity, once a random port is used for binding where a listener is listening, how does the client know which port to connect to at the listener site? Is this conveyed out of band?

**Comment by mrocklin** [comment]
> Is this conveyed out of band?

Sort of.  Dask is peer to peer, with a single known peer whose address is conveyed out of band.  Everyone else connects to this central listener (we call this the scheduler) and tells that central listener the address on which they are listening.  When two peers need to communicate to each other the central scheduler tells them the relevant addresses.
