### ISSUE TITLE
How to gracefully close a endpoint?

### ISSUE THREAD

**Issue by mrocklin** [Akshay-Venkatesh/ucx-py#81]
When I want to close an connection, I would prefer to signal to the other end that we're done, then wait for all remaining messages to come through, and then finally close things.  Is there a clean way to do this?

**Comment by Akshay-Venkatesh** [comment]
Today we use this:
```
ucp_py/_libs/src/ucp_py_ucp_fxns.c:    close_req = ucp_ep_close_nb(*ep_ptr, UCP_EP_CLOSE_MODE_FORCE);
```
But we can switch over to [this](https://github.com/openucx/ucx/blob/master/src/ucp/api/ucp.h#L282) to flush out local outstanding operations.

I'm not sure how we can achieve this for remote outstanding operations though because we would need to define what _remaining_ messages mean. I can check on this and get back.
